"""create database

Revision ID: e25ee4af927d
Revises: 
Create Date: 2026-02-09 16:09:37.196536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25ee4af927d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('clear_pm', sa.String(), nullable=False),
    sa.Column('ref_qtd_sum', sa.Integer(), nullable=False),
    sa.Column('ref_freq_sum', sa.Integer(), nullable=False),
    sa.Column('ref_formal_sum', sa.Integer(), nullable=False),
    sa.Column('ref_informal_sum', sa.Integer(), nullable=False),
    sa.Column('nc_total_sum', sa.Integer(), nullable=False),
    sa.Column('opened_nc_sum', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('situation', sa.Enum('IMPROVING', 'STABLE', 'WORSING', name='situationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COMUNITY', name='userpermission'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('audit_results')
    # ### end Alembic commands ###
